export interface officeDetail {
    key?: string,
    name: string,
    contactFirstName?: string,
    contactLastName?: string,
    addressType?: number,
    usAddress?: any,
    foreignAddress?: any,
    address?: any,
    isPredefined?: boolean,
    efin?: string,
    efinStatus?: number,
    planningToUseBankProduct?: boolean
}

export interface userDetail {
    key?: string,
    firstName?: string,
    lastName?: string,
    phoneNo?: string,
    isActiveUser?: boolean,
    email?: string,
    recoveryEmail?: string,
    secondaryEmail?: boolean,
    userType?: Array<number>,
    PTIN?: string,
    STIN?: string,
    PPIN?: string,
    preparerId?: string,
    NYTPRIN?: string,
    NY_ExemptCode?: string,
    NM_CRS?: string,
    OR_LicenseNumber?: string,
    ssn?: string,
    ein?: string,
    isSelfEmployed?: boolean,
    firmName?: string,
    sameAsOfficeAddress?: boolean,
    address?: any,
    twoFactorAuthentication?: any,
    twoFactorAuthType?: number,
    locations?: any,
    isPreparer?: boolean,
    isERO?: boolean,
    isLoggedInUser?: boolean,
    isPhoneVerified?: boolean,
    isActivated?: boolean,
    efinStatus?: number,
    EfinEfilingStatus?: number,
    userVerified?: boolean
    documentId?: string,
    isEmailVerified?: boolean,
    isSecondaryEmailVerified?: boolean,
    preparerPhone?: string,
    preparerEmail?: string,
    isPreparerEmailSameAsLogin?: boolean,
    isPreparerPhoneSameAsLogin?: boolean,
    efinToUse?: any,
    signatureImage?: string,
    isAdministrator?: boolean,
    locationsToUseEfin?: Array<string>,
    thirdPartyDesignee?: boolean,
    efilingStates?: Array<any>,
    isNYEfileState?: boolean,
    isNMEfileState?: boolean,
    isOREfileState?: boolean,
    isContractContact?: boolean,
    userImageSrc?: string,
    profilePhoto?: string,
    isAssociatedWithEfin?: boolean,
    signatures?: Array<any>,
    showReturn?: number,
    encryptedEmail?: string
}

export interface officeOverviewDetail {
    officeList?: Array<officeDetail>,
    userList?: Array<userDetail>,
    administrator?: any,
    contractContact?: any,
    licenseOwner?: any,
    serviceBureau?: any
}

export interface efinDetail {
    efin?: string,
    trackingNumber?: string,
    isActive?: boolean,
    effectiveDate?: string,
    firmName?: string,
    isFirmNameSameAsFirm?: boolean,
    firmEIN?: string,
    isEINSameAsFirm?: boolean,
    firmAddress?: any,
    isAddressSameAsFirm?: boolean,
    efinToUseInOffice?: Array<string>,
    associatedUsers?: Array<string>,
    efinStatus?: number,
    dispalyedLocations?: Array<any>,
    displayedEROS?: Array<any>,
    id?: string,
    documentId?:string
}